version: '3.5'
services:
  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./funcao.sql:/docker-entrypoint-initdb.d/funcao.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
#    deploy:
#      resources:
#        limits:
#          cpus: "0.13"
#          memory: "140MB"