version: "3.5"

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./1-init.sql:/docker-entrypoint-initdb.d/1-init.sql
      - ./funcao.sql:/docker-entrypoint-initdb.d/funcao.sql
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.33"
          memory: "300MB"

  api01: &api
    image: rinha
    hostname: api01
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "100MB"

  api02:
    <<: *api
    hostname: api02
    restart: on-failure
    ports:
      - "8082:8080"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1